# Generated by Django 4.1.5 on 2024-01-05 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_source', models.CharField(max_length=255, null=True)),
                ('post_source_id', models.CharField(max_length=255, null=True)),
                ('post_author', models.CharField(default='', max_length=255)),
                ('post_title', models.TextField(default='')),
                ('post_description', models.TextField(default='')),
                ('post_original_url', models.TextField(default='')),
                ('url_to_image', models.TextField(default='')),
                ('post_content', models.TextField(default='')),
                ('post_slug', models.CharField(default='', max_length=255)),
                ('time_created', models.DateTimeField()),
                ('time_created_text', models.CharField(default='', max_length=255)),
                ('net_views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=50)),
                ('user_fname', models.CharField(default='', max_length=50)),
                ('user_lname', models.CharField(default='', max_length=50)),
                ('user_profile_image_url', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField(default='')),
                ('time_created', models.DateTimeField()),
                ('post_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='api.posts')),
                ('user_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
