# Generated by Django 4.1.5 on 2024-01-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_id', models.IntegerField()),
                ('comment_text', models.TextField()),
                ('time_created', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_title', models.TextField()),
                ('post_content', models.TextField()),
                ('post_slug', models.CharField(max_length=255)),
                ('time_created', models.IntegerField()),
                ('net_views', models.IntegerField(default=0)),
            ],
        ),
    ]
