# Generated by Django 4.1.5 on 2024-01-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_comments_post_id_alter_comments_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time_created',
            field=models.DateTimeField(null=True),
        ),
    ]
