# Generated by Django 4.1.5 on 2024-01-02 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_comments_comment_id_alter_posts_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_author',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_original_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='posts',
            name='url_to_image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_slug',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_title',
            field=models.TextField(default=''),
        ),
    ]
